FROM okworx/sodabuilder:11 AS builder

WORKDIR /opt/soda4LCA/

# Grab whole project src (Node, Registry, etc... )
COPY . .

# Re-Build Node/target/Node.war
RUN mvn -B --no-transfer-progress clean package -pl Node -am -DskipTests -DskipITs -DskipCargo

FROM tomcat:9-jdk11-temurin

LABEL \
	Maintainer = "ok*worx <info@okworx.com>" \
	MailingList = "soda4LCA@lists.kit.edu" \
	License = "GNU Affero General Public License (AGPL) 3.0" \
	Purpose = "Generic/Production-ready soda4LCA Node"

WORKDIR /soda

# install curl, Open JDK
RUN set -x \
	&& apt update && apt install -y \
	gettext \
	default-mysql-client \
	&& rm -rf /var/lib/apt/lists/*

# create upload and data folders
RUN mkdir -p /opt/soda/data/datafiles \
	&& mkdir -p /opt/soda/data/validation_profiles \
	&& mkdir -p /opt/soda/data/tmp/uploads \
	&& mkdir -p /opt/soda/data/tmp/zips

ENV CATALINA_BASE /usr/local/tomcat

# disable default logging (JULI). log4j will take it's place
RUN rm ${CATALINA_BASE}/conf/logging.properties

# download and put the MySQL driver into the tomcat libraries
RUN curl -O https://cdn.mysql.com/Downloads/Connector-J/mysql-connector-j-8.4.0.tar.gz \
	&& mkdir connector-j \
	&& tar xvf mysql-connector-j-*.tar.gz -C connector-j --strip-components=1 \
	&& mv connector-j/mysql-connector-*.jar ${CATALINA_BASE}/lib \
	&& rm -rf connector-j \
	&& rm mysql-connector-j-*.tar.gz

ENV CONFIG_DIR .docker/Node/stable

# copy configuration files
COPY ${CONFIG_DIR}/server.xml.template ${CONFIG_DIR}/web.xml.template ${CATALINA_BASE}/conf/
# copy properties file to /soda and at runtime (if file does not exist yet!) to /opt/soda
# this ensures that on initial startup of the container, the directory /opt/soda can be mounted
COPY ${CONFIG_DIR}/soda4LCA.properties.template /soda/soda4LCA.properties.template

# adding the startup script
COPY ${CONFIG_DIR}/start.sh /soda
RUN chmod +x start.sh

# copy the webapp from builder stage
COPY --from=builder /opt/soda4LCA/Node/target/Node.war ${CATALINA_BASE}/webapps/ROOT.war

# sudo docker run -it --rm -p 80:8080 soda
CMD [ "/soda/start.sh" ]
