#version: "3"

services:
  soda:
    image: okworx/soda4lca:7.14.0
    ports:
      - "8080:8080" 
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_DATABASE: epdm
      MYSQL_USER: root
      MYSQL_PASSWORD: admin@123
    volumes:
      - "./soda4lca:/opt/soda"
    container_name: soda
    networks:
      - epdm-network


  epdm:
    build:
      context: ./epdm
      dockerfile: Dockerfile
    container_name: epdm
    ports:
      - "8082:8082"
    environment:
      SPRING_application_name: epdm
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/epdm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin@123
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL-AUTO: none
      SPRING_JPA_SHOW_SQL: 	true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SERVER_PORT: 8082
      SERVER_ADDRESS: 0.0.0.0
      SPRING_SQL_INIT_MODE: always
    networks:
      - epdm-network

networks:
  epdm-network:
    driver: bridge