SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

DROP TABLE IF EXISTS `t_user`;
CREATE TABLE `t_user` (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  LOGIN varchar(255) DEFAULT NULL,
  PASSWORD varchar(64) DEFAULT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY LOGIN (LOGIN)
) ENGINE=innodb DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS `t_node`;
CREATE TABLE `t_node` (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NAME varchar(255) NOT NULL,
  DESCRIPTION varchar(255) DEFAULT NULL,
  NODEID varchar(255) NOT NULL,
  BASEURL varchar(255) NOT NULL,
  ADMINNAME varchar(255) DEFAULT NULL,
  ADMINEMAILADDRESS varchar(255) DEFAULT NULL,
  ADMINPHONE varchar(255) DEFAULT NULL,
  ADMINWEBADDRESS varchar(255) DEFAULT NULL,
  STATUS varchar(20) DEFAULT NULL,
  NODE_CREDENTIALS_ID bigint(20),
  REGISTRY_CREDENTIALS_ID bigint(20),
  PRIMARY KEY (ID),
  UNIQUE KEY BASEURL (BASEURL),
  UNIQUE KEY NODEID (NODEID)
) ENGINE=innodb DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `t_node_credentials`;
CREATE TABLE `t_node_credentials` (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  ACCESSPASSWORD BLOB,
  ACCESSACCOUNT varchar(255) DEFAULT NULL,
  NODEID varchar(255) NOT NULL,
  UNIQUE KEY NODEID (NODEID),
  PRIMARY KEY (ID)
) ENGINE=innodb DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

ALTER TABLE `t_node` ADD CONSTRAINT FK_NODE_NODE_CRED_ID FOREIGN KEY (NODE_CREDENTIALS_ID) REFERENCES `t_node_credentials` (ID);

DROP TABLE IF EXISTS `t_registry_credentials`;
CREATE TABLE `t_registry_credentials` (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  ACCESSPASSWORD BLOB,
  ACCESSACCOUNT varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=innodb DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

ALTER TABLE `t_node` ADD CONSTRAINT FK_NODE_REG_CRED_ID FOREIGN KEY (REGISTRY_CREDENTIALS_ID) REFERENCES `t_registry_credentials` (ID);

DROP TABLE IF EXISTS `t_node_change_log`;
CREATE TABLE `t_node_change_log` (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NODEID varchar(255) NOT NULL,
  OPERATIONTYPE varchar(20) DEFAULT NULL,
  OPERATIONDATE timestamp,
  PRIMARY KEY (ID)
) ENGINE=innodb DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


DROP TABLE IF EXISTS `t_nonce`;
CREATE TABLE `t_nonce` (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  USEDATE timestamp,
  VALUE VARBINARY(80),
  UNIQUE KEY VALUE (VALUE),
  PRIMARY KEY (ID)
) ENGINE=innodb DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


DROP TABLE IF EXISTS `t_data_set`;
CREATE TABLE `t_data_set` (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  UUID varchar(255),
  NAME varchar(255),
  NODE_ID bigint(20),
  HASH VARBINARY(16),
  OWNER varchar(255),
  USER_ varchar(255),
  USER_EMAIL varchar(255),
  STATUS varchar(20) DEFAULT 'NEW',
  VERSION varchar(255),
  PRIMARY KEY (ID)
) ENGINE=innodb DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

ALTER TABLE `t_data_set` ADD CONSTRAINT FK_DS_NODE_ID FOREIGN KEY (NODE_ID) REFERENCES `t_node` (ID);

DROP TABLE IF EXISTS `t_data_set_compliance_uuids`;
CREATE TABLE `t_data_set_compliance_uuids` (
  DS_ID bigint,
  UUID varchar(255)
) ENGINE=innodb DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `t_compliance`;
CREATE TABLE `t_compliance` (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NAME varchar(255),
  UUID varchar(255),
  PRIMARY KEY (ID)
) ENGINE=innodb DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `t_node_audit_log`;
CREATE TABLE `t_node_audit_log` (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NODEID bigint(20),
  OPERATIONTIME bigint(20),
  OPERATIONTYPE varchar(40),
  OBJECTNAME varchar(255),
  PRIMARY KEY(ID)
) ENGINE=innodb DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `t_data_set_audit_log`;
CREATE TABLE `t_data_set_audit_log` (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  DATASETID bigint(20),
  UUID varchar(40),
  VERSION varchar(15),
  NODE_AUDIT_LOG_ID bigint(20),
  PRIMARY KEY(ID)
) ENGINE=innodb DEFAULT CHARSET=utf8;

ALTER TABLE `t_data_set_audit_log` ADD CONSTRAINT FK_NODE_AUDIT_LOG_ID FOREIGN KEY (NODE_AUDIT_LOG_ID) REFERENCES `t_node_audit_log` (ID);