version: "3"

services:
  soda:
    image: okworx/soda4lca:5.9.3
    ports:
      - "80:8080" #the internal port is 8080 and 80 the exposed
    environment:
      MYSQL_HOST: mysqld
      MYSQL_DATABASE: soda
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - "./soda4lca/:/opt/soda/:rw"
  mysqld:
    image: mysql/mysql-server:5.7
    command: --bind-address=0.0.0.0 --character-set-server=utf8 --collation-server=utf8_general_ci --max_allowed_packet=25M --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: soda
      MYSQL_ROOT_HOST: "%"
