package de.iai.ilcd.service.glad.model;

public enum CarbonStorageModeling {
    INCLUDED_AND_DISTINGUISHED_CORRECTION, INCLUDED_AND_DISTINGUISHED_OTHER, INCLUDED_AND_NOT_VISIBLE, NOT_INCLUDED, UNKNOWN, NOT_APPLICABLE;

}
