package de.iai.ilcd.service.glad.model;

public enum SourceReliability {
    MEASURED_VERIFIED, PARTLY_MEASURED_VERIFIED, PARTYLY_MEASURED_PARTLY_ESTIMATED, ESTIMATED_QUALIFIED, ESTIMATED_UNQUALIFIED

}
