package de.iai.ilcd.jaxb;

import de.iai.ilcd.util.UnmarshalHelper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import java.io.StringReader;

/**
 * Same idea as UnmarshalHelper but:
 *
 * <ol>
 * <li>It uses the fresh stubs that has been generated by mvn jaxb2:xjc and not the ones from ilcd-api.</li>
 * <li>It doesn't wastefully create expensive JAXBContext every time it need a marshaler.</li>
 * </ol>
 *
 * @author MK
 * @see UnmarshalHelper
 * @since soda4LCA 6.8.1
 */
@Component
public class DataSetJAXB {

    private Unmarshaller jaxb;

    @Autowired
    DataSetJAXB(Unmarshaller jaxb) {
        this.jaxb = jaxb;
    }

    public Object unmarshal(String payload) {
        try {
            return jaxb.unmarshal(new StringReader(payload));
        } catch (JAXBException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        return null;
    }


}
