CREATE TABLE IF NOT EXISTS epdm.portal_exported_xml (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  	`XMLFILE_ID` bigint(20) DEFAULT NULL,
    `IS_EXPORTED` tinyint(1) DEFAULT '0',
  	`UUID` varchar(255) DEFAULT NULL,
    DATA_SET_TYPE VARCHAR(100) NOT NULL UNIQUE,
  	KEY `FK_process_XMLFILE_ID` (`XMLFILE_ID`),
  	CONSTRAINT `FK_portal_exported_xml_XMLFILE_ID` FOREIGN KEY (`XMLFILE_ID`) REFERENCES `xmlfile` (`ID`)
);
